# Generated by Django 5.0.4 on 2024-04-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_problem_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='img',
            new_name='image',
        ),
    ]
